package model.events;

public enum EventType {
    SOLDIER_CHARGE,
    CAVALRY_CHARGE,
    CAVALRY_RUNNING,
    SOLDIER_MARCHING,
    SOLDIER_FIGHTING,
    EXPLOSION,
    BALLISTA_HIT_GROUND,
    BALLISTA_HIT_FLESH,
}
