package view.audio;

public enum AudioType {
    LEFT_CLICK,
    RIGHT_CLICK,
    CAVALRY_RUNNING,
    CAVALRY_CHARGE,
    SOLDIER_CHARGE,
    SOLDIER_FIGHTING,
    SOLDIER_MARCHING,
    EXPLOSION,
    BALLISTA_HIT_GROUND,
    BALLISTA_HIT_FLESH,
    ARROW_CROWD_HIT
}
